export const dashboard = <i class="fa fa-line-chart"></i>;
export const transactions = <i class="fa fa-credit-card"></i>
export const categories = <i class="fa fa-tag"></i>
export const accounts = <i className="fa fa-wallet"></i>
export const settings = <i class="fa fa-cog"></i>
export const logout = <i class="fa fa-sign-out"></i>
export const trend = <i class="fi fi-tr-money-bill-wave-alt"></i>
export const expenses = <i class="fa fa-exchange"></i>
export const money =<i class='fas fa-money-bill'></i>
export const freelance = <i class="fa fa-globe"></i>
export const stocks = <i className="fa fa-line-chart"></i>
export const bitcoin = <i class="fa fa-bitcoin"></i>
export const piggy = <i class="fa fa-bank"></i>
export const yt = <i class="fa fa-youtube-play"></i>
export const card = <i class="fa fa-cc-visa"></i>
export const users = <i class="fa fa-user"></i>
export const rupee = <i class="fa fa-rupee"></i>
export const calender = <i class="fa fa-calendar"></i>
export const comment = <i class="fa fa-comments-o"></i>
export const plus = <i class="fa fa-plus"></i>
export const trash = <i class="fa fa-trash-o"></i>
export const signout = <i class="fa fa-sign-out"></i>
export const takeaway = <i class='fas fa-utensils'></i>
export const clothing = <i class='fas fa-tshirt'></i>
export const book = <i class="fa fa-book"></i>
export const food = <i className="fa-solid fa-bowl-food"></i>
export const medical = <i class="fa fa-briefcase"></i>
export const tv = <i class="fa fa-tv"></i>
export const circle = <i class="fa fa-dot-circle-o"></i>